// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SigmaCoreProject.Models;

namespace SigmaCoreProject.Migrations
{
    [DbContext(typeof(sigmaCoreContext))]
    [Migration("20190617215355_CreateIdasdensss")]
    partial class CreateIdasdensss
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SigmaCoreProject.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BodyComment");

                    b.Property<DateTime?>("DateComent")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdNews");

                    b.Property<int?>("IdParentComent");

                    b.Property<string>("IdUser")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SigmaCoreProject.Models.Favorites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdNews");

                    b.Property<int>("IdPers");

                    b.Property<string>("IdUser")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("SigmaCoreProject.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BodyNews");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateEndVisible")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateStartVisible")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("datetime");

                    b.Property<string>("IdUserCreate")
                        .HasMaxLength(500);

                    b.Property<bool?>("IsVisible");

                    b.Property<string>("SeoDesc")
                        .HasMaxLength(500);

                    b.Property<string>("SeoTitlte")
                        .HasMaxLength(500);

                    b.Property<string>("ShoreInfo")
                        .HasMaxLength(500);

                    b.Property<string>("TitleNews")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("SigmaCoreProject.Models.OtherContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BodyContent");

                    b.Property<int>("IdPhysPer");

                    b.Property<int>("IdTypeContent");

                    b.Property<string>("IdUserCreate")
                        .HasMaxLength(50);

                    b.Property<bool>("IsVislbe");

                    b.Property<string>("TitleContent")
                        .HasMaxLength(5000);

                    b.HasKey("Id");

                    b.ToTable("OtherContent");
                });

            modelBuilder.Entity("SigmaCoreProject.Models.PhysPers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateDb")
                        .HasColumnType("datetime");

                    b.Property<string>("IdUser")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasMaxLength(500);

                    b.Property<string>("Patronymic")
                        .HasMaxLength(500);

                    b.Property<string>("Surname")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("PhysPers");
                });

            modelBuilder.Entity("SigmaCoreProject.Models.RankNews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IdUser")
                        .HasMaxLength(500);

                    b.Property<decimal?>("Rank")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("idPhysPers");

                    b.HasKey("Id");

                    b.ToTable("RankNews");
                });

            modelBuilder.Entity("SigmaCoreProject.Models.S_TypeContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeConent")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("STypeContent");
                });
#pragma warning restore 612, 618
        }
    }
}
