// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SigmaCoreProject.Models;

namespace SigmaCoreProject.Migrations
{
    [DbContext(typeof(sigmaCoreContext))]
    partial class sigmaCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SigmaCoreProject.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BodyComment");

                    b.Property<DateTime?>("DateComent")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdNews");

                    b.Property<int?>("IdParentComent");

                    b.Property<string>("IdUser")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SigmaCoreProject.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BodyNews");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateEndVisible")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateStartVisible")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnType("datetime");

                    b.Property<string>("IdUserCreate")
                        .HasMaxLength(500);

                    b.Property<bool?>("IsVisible");

                    b.Property<string>("SeoDesc")
                        .HasMaxLength(500);

                    b.Property<string>("SeoTitlte")
                        .HasMaxLength(500);

                    b.Property<string>("ShoreInfo")
                        .HasMaxLength(500);

                    b.Property<string>("TitleNews")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("News");
                });
#pragma warning restore 612, 618
        }
    }
}
